spring:
  application:
    name: weeklymealplanner


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

kroger:
  base-url: ${KROGER_BASE_URL:https://api.kroger.com}
  oauth-token-path: /v1/connect/oauth2/token
  authorization-path: /v1/connect/oauth2/authorize
  locations-path: /v1/locations
  products-path: /v1/products
  identity-profile-path: /v1/identity/profile
  cart-add-path: /v1/cart/add
  client-id: ${KROGER_CLIENT_ID}
  client-secret: ${KROGER_CLIENT_SECRET}
  scope: product.compact
  redirect-uri: ${KROGER_REDIRECT_URI:http://localhost:8080/api/v1/kroger/oauth/callback}
  user-scope: ${KROGER_USER_SCOPE:profile.compact cart.basic:write product.compact}
